# -*- coding: utf-8 -*-
"""Reto#2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yviyKJaO9al3ZijFPaGQxE3c9I0efphY
"""

#Programa de registro de usuarios

import json

def cantidad_usuarios():
    while True:
        try:
            cantidadUsuarios = int(input("¿Cuántos usuarios desea agregar? "))
            return cantidadUsuarios  # Devuelve la cantidad de usuarios si la entrada es válida
        except ValueError:
            print("Por favor ingresa un número válido")


def obtener_nombre():
    while True:
        nombre = input("Nombre: ")
        if 5 <= len(nombre) <= 50:
            return nombre
        else:
            print("El nombre debe tener entre 5 y 50 caracteres.")

def obtener_apellido():
    while True:
        apellido = input("Apellido: ")
        if 5 <= len(apellido) <= 50:
            return apellido
        else:
            print("El apellido debe tener entre 5 y 50 caracteres.")

def obtener_telefono():
    while True:
        telefono = input("Teléfono: ")
        if len(telefono) == 10:
            return telefono
        else:
            print("El teléfono debe tener 10 dígitos.")

def obtener_mail():
    while True:
        mail = input("Correo electrónico: ")
        if 5 <= len(mail) <= 50:
            return mail
        else:
            print("El correo electrónico debe tener entre 5 y 50 caracteres.")

def registro_usuarios(numero_usuarios):
    diccionario_de_usuarios = {}

    # Bucle para registrar usuarios
    for contador in range(numero_usuarios):
        usuario = {"nombre": obtener_nombre(),
                   "apellido": obtener_apellido(),
                   "telefono": obtener_telefono(),
                   "mail": obtener_mail()}
        diccionario_de_usuarios[contador] = usuario

    return json.dumps(diccionario_de_usuarios, sort_keys=True, indent=4)

print("Bienvenido al programa de registro de usuarios: ")
usuarios_registrados = registro_usuarios(cantidad_usuarios())
print("Usuarios registrados:", usuarios_registrados)